### PR TITLE
Update UI on Chats page

### PR DESCRIPTION
**Pull request by shirokov-kirill**

### CODE REVIEW

**Review by app1606 — APPROVED** [review]

**Comment by J3ne4ek** [comment]
There is no "send" button and I don't know what three dots button mean in context of chat. Also I occur error when I try to get chat page

```bash
Request failed with status code 401
AxiosError: Request failed with status code 401
    at settle (http://localhost:3000/static/js/bundle.js:150795:12)
    at XMLHttpRequest.onloadend (http://localhost:3000/static/js/bundle.js:149455:66)
    at Axios.request (http://localhost:3000/static/js/bundle.js:149956:41)
    at async http://localhost:3000/static/js/bundle.js:4048:20
```

It looks like a problem with an auth token on this page. Could you check it?

**Comment by shirokov-kirill** [comment]
I wasn't able to test connectivity in my current configuration as the docker script didn't work for me. It might work now though because I added the authToken in the header. I'll be able to have a closer look at the connection problem soon.

I wrapped send logic under the try-catch so that the page is still available with default data and the error doesn't fail the screen

**Comment by shirokov-kirill** [comment]
Now, with token, works fine for me on VM

**Comment by shirokov-kirill** [comment]
Chats can be fetched properly now

**Pull request merged**
